services:
  Mooc.Courses.Domain.MongoCourseRepository:
    class: ../../../../../../Contexts/Mooc/Courses/Infrastructure/Persistence/Mongo/MongoCourseRepository
    arguments: ['@Mooc.Shared.ConnectionManager']

  Mooc.Courses.Application.CourseCreator:
    class: ../../../../../../Contexts/Mooc/Courses/Application/CourseCreator
    arguments: ['@Mooc.Courses.Domain.MongoCourseRepository']
