services:
  Mooc.Shared.MongoConfig:
    factory:
      class: ../../../../../../Contexts/Mooc/Shared/Infrastructure/Persistence/MongoConfigFactory
      method: 'createConfig'

  Mooc.Shared.ConnectionManager:
    factory:
      class: ../../../../../../Contexts/Shared/Infrastructure/Persistence/Mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['mooc', '@Mooc.Shared.MongoConfig']
