services:
  Mooc.Shared.Config:
    factory:
      class: ../../../../../../Contexts/Mooc/Shared/Infrastructure/Persistence/MongoConfigFactory
      method: 'createConfig'

  Mooc.Shared.ConnectionManager:
    factory:
      class: ../../../../../../Contexts/Shared/Infrastructure/Persistence/Mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['mooc', '@Mooc.Shared.Config']

  Mooc.Shared.EventBus:
    class: ../../../../../../Contexts/Shared/Infrastructure/EventBus/InMemory/InMemoryEventBus
    arguments: []
