services:
  Mooc.MongoConfig:
    factory:
      class: ../../../../../../Contexts/Mooc/Shared/Infrastructure/Persistence/MongoConfigFactory
      method: 'createConfig'

  Mooc.ConnectionManager:
    factory:
      class: ../../../../../../Contexts/Shared/Infrastructure/Persistence/Mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['mooc', '@Mooc.MongoConfig']
