imports:
  - { resource: ./application.yaml }

services:
  Mooc.MongoEnvironmentArranger:
    class: ../../../../../../tests/Contexts/Shared/Infrastructure/Persistence/Mongo/MongoEnvironmentArranger
    arguments: ['@Mooc.Shared.ConnectionManager']
